name: test

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-version: Pharo64-8.0
      - run: (sudo apt-get install build-essential gcc-multilib ; smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-version }})
        shell: bash
        timeout-minutes: 25
